openapi: 3.0.1
info:
  title: PPAP API docs
  description: PPAP API서버 명세페이지입니다.
  version: 0.0.1
servers:
- url: http://localhost:8080
tags: []
paths:
  /auth/reissue:
    post:
      tags:
      - auth
      operationId: reissue/reissue_test
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/auth-kakao-login486549215'
            examples:
              reissue/reissue_test_fail_invalid_token:
                value: |-
                  {
                    "refreshToken" : "testToken"
                  }
              reissue/reissue_test_fail_no_token:
                value: |-
                  {
                    "refreshToken" : null
                  }
              reissue/reissue_test:
                value: |-
                  {
                    "refreshToken" : "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJyanNkbnhvZ2hAbmF2ZXIuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImlkIjoxLCJleHAiOjIwMDY5NDA1MDN9.kuTltCxbmWuc7Y5Nqpl0OQm4Wo1EodXPRA-R9lB36EMN67Ti4DCqz5q8SihpbImpxyD9VPVK_fo4waCD_BN0pg"
                  }
      responses:
        "404":
          description: "404"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/auth-kakao-login486549215'
              examples:
                reissue/reissue_test_fail_invalid_token:
                  value: |-
                    {
                      "success" : false,
                      "response" : null,
                      "error" : {
                        "message" : "존재하지 않는 토큰입니다.",
                        "status" : 404
                      }
                    }
        "400":
          description: "400"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/auth-kakao-login486549215'
              examples:
                reissue/reissue_test_fail_no_token:
                  value: |-
                    {
                      "success" : false,
                      "response" : null,
                      "error" : {
                        "message" : "must not be null",
                        "status" : 400
                      }
                    }
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/auth-kakao-login486549215'
              examples:
                reissue/reissue_test:
                  value: |-
                    {
                      "success" : true,
                      "response" : {
                        "accessToken" : "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOm51bGwsInJvbGUiOiJST0xFX1VTRVIiLCJpZCI6MSwiZXhwIjoxNjkxNTgyMzA0fQ._NJHVxKeCn18crjSL9jhDKZV5T-D_UBfuEUHTOssWVpDwjBc6mTUEmNqlMB2V_OiVzyED5yslkrAcQG2gqHNBg",
                        "refreshToken" : "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOm51bGwsInJvbGUiOiJST0xFX1VTRVIiLCJpZCI6MSwiZXhwIjoyMDA2OTQwNTA0fQ.6LZEf0oXgeZdiJRw1tUNKSqTjm-13UEonfrmDMCRcI4lYKEGcPWP3Bvf2tMGLXZN8ZuaylkE1ujEPqOaMl6zzw"
                      },
                      "error" : null
                    }
  /auth/kakao/login:
    post:
      tags:
      - auth
      summary: 카카오 로그인API
      description: 카카오 로그인API
      operationId: user-login/user_kakao_login_test
      parameters:
      - name: Kakao
        in: header
        description: "카카오 Access토큰: 카카오 액세스 토큰을 넣어야 합니다.(그대로 입력시 에러발생)"
        required: true
        schema:
          type: string
        example: testToken
      responses:
        "400":
          description: "400"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/auth-kakao-login486549215'
              examples:
                user-login/user_kakao_login_test_fail_invalid_kakao_access_token:
                  value: |-
                    {
                      "success" : false,
                      "response" : null,
                      "error" : {
                        "message" : "유효하지 않은 카카오 accessToken입니다.",
                        "status" : 400
                      }
                    }
                user-login/user_kakao_login_test_fail_kakao_access_token_missing:
                  value: |-
                    {
                      "success" : false,
                      "response" : null,
                      "error" : {
                        "message" : "카카오 accessToken을 입력해주세요",
                        "status" : 400
                      }
                    }
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/auth-kakao-login486549215'
              examples:
                user-login/user_kakao_login_test:
                  value: |-
                    {
                      "success" : true,
                      "response" : {
                        "accessToken" : "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJyanNkbnhvZ2hAbmF2ZXIuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImlkIjoxLCJleHAiOjE2OTE1ODIzMDR9.m8PHRIjOGZW0YuaJKGq6voWA_p52KYDFQyXk14FBv6WP5sctm0BN0P4zyKyP_usGBX3kCJYnxjEJTVfxLCn1dw",
                        "refreshToken" : "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJyanNkbnhvZ2hAbmF2ZXIuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImlkIjoxLCJleHAiOjIwMDY5NDA1MDR9.2b579F37M3cMqOesmdaBUIyznC7ZZKMPdZQ8dWZ55eBekOG04giyh78X5GxS8sEANGQ0tyYkj6YffNzX-AiZxw"
                      },
                      "error" : null
                    }
components:
  schemas:
    auth-kakao-login486549215:
      type: object
