version: "3"
services:
  redis:
    image: redis:alpine
    container_name: redis_prod
    hostname: redis
    ports:
      - "6379:6379"


  nginx:
    image: ${ECR_NGINX_IMAGE_URL}
    container_name: server_nginx
    ports:
      - "80:80"
    volumes:
      - ./:/app/
      - ./conf/nginx:/etc/nginx/conf.d
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - ppap
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  ppap:
    image: ${ECR_PPAP_IMAGE_URL}
    ports:
      - "8080:8080"
    container_name: web_prod
    env_file:
      - ./.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./log:/opt/ppap/log
      - ./src/main/resources:/opt/ppap/src/main/resources
    tty: true
    restart: on-failure:2
    depends_on:
      - redis
      - database

