server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URI_PROD}
    username: admin
    password: ${DATABASE_PASSWORD_PROD}

  jpa:
    hibernate:
      ddl-auto: none
#    show-sql: true
    properties:
      hibernate:
#        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: false

  data:
    redis:
      host: redis
      port: 6379

  mail:
    host: smtp.gmail.com
    username: ${GMAIL_USER}
    password: ${GMAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          socketFactory.class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
    admin: ${ADMIN_EMAIL}

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never

access-jwt-secret-key: ${ACCESS_TOKEN}
refresh-jwt-secret-key: ${REFRESH_TOKEN}

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    secret: ${KAKAO_SECRET}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false