name: Deploy Workflow

on:
  push:
    branches: 
      - main

env:
  IMAGE_TAG: latest
  NCR_REPOSITORY: ${{ secrets.NCR_REPOSITORY }}
  NCP_CLI_VERSION: CLI_1.1.20_20240620

defaults:
  run:
    working-directory: ./ppap

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: get Github Action Public IP
        id: ip
        uses: haythem/public-ip@v1.3
  

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure NCP credentials
        run: |
          cd ~
          wget https://www.ncloud.com/api/support/download/files/cli/CLI_1.1.20_20240620.zip
          unzip CLI_1.1.20_20240620.zip
          mkdir ~/.ncloud
          echo -e "[DEFAULT]\nncloud_access_key_id=${{secrets.NCP_ACCESS_TOKEN}}\nncloud_secret_access_key=${{secrets.NCP_SECRETS_TOKEN}}\nncloud_api_url=https://ncloud.apigw.ntruss.com" >> ~/.ncloud/configure
          chmod 755 ~/$NCP_CLI_VERSION/cli_linux/ncloud

      - name: docker build
        run: |
          echo ${{ secrets.NCP_SECRETS_TOKEN }} | docker login --username ${{ secrets.NCP_ACCESS_TOKEN }} --password-stdin
          docker build -t $NCR_REPOSITORY:$IMAGE_TAG -f DockerFileProd .
          docker push $NCR_REPOSITORY:$IMAGE_TAG

      - name: add Github Actions IP to ACG
        run: |
          cd ~/$NCP_CLI_VERSION/cli_linux
          ./ncloud vserver addAccessControlGroupInboundRule --regionCode KR --vpcNo ${{ secrets.NCP_VPC_NO }} --accessControlGroupNo ${{ secrets.NCP_ACG_NO }} --accessControlGroupRuleList "protocolTypeCode='TCP', ipBlock='${{ steps.ip.outputs.ipv4 }}  ', portRange='22'"
          
      - name: deploy NCP server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USER_NAME }}
          key: ${{ secrets.NCP_SSH_KEY }}
          script: |
            cd ~/api-server/ppap
            sudo git pull
            sudo echo ${{ secrets.NCP_SECRETS_TOKEN }} | docker login --username ${{ secrets.NCP_ACCESS_TOKEN }} --password-stdin
            sudo docker compose -f docker-compose.prod.yml pull
            sudo docker compose -f docker-compose.prod.yml down ppap
            sudo docker compose -f docker-compose.prod.yml up -d
            sudo docker image prune -f

      - name: remove github Actions IP from ACG
        run: |
          cd ~/$NCP_CLI_VERSION/cli_linux
          ./ncloud vserver removeAccessControlGroupInboundRule --regionCode KR --vpcNo ${{ secrets.NCP_VPC_NO }} --accessControlGroupNo ${{ secrets.NCP_ACG_NO }} --accessControlGroupRuleList "protocolTypeCode='TCP', ipBlock='${{ steps.ip.outputs.ipv4 }}', portRange='22'"