name: Deploy Workflow

on:
  push:
    branches: ['main', 'test/testCD']


env:
  AWS_REGION: ap-northeast-2
  IMAGE_TAG: latest
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

defaults:
  run:
    working-directory: ./ppap

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{ secrets.AWS_SECRETS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr


      - name: docker build
        env: 
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}

        run: |
          echo "$REGISTRY/$ECR_REPOSITORY"
          docker build -t $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f DockerFileProd .
          
      
